/* Every word a person reads; no other file in `src/` holds one. */
export const t = {
  app: 'Setup Finder',
  skipToRoom: 'Skip to the room',

  notBuilt: 'Not built yet',
  noGame: 'No game is connected',
  goToIt: 'Go to it',

  /* Bar */
  moves: 'Moves',
  options: 'Options',
  connect: 'Connect',
  disconnect: 'Disconnect',
  working: 'Working',

  emulators: 'Emulators',
  processCol: 'Process',
  stateCol: 'State',
  runningWord: 'Running',
  pausedWord: 'Paused',
  chooseOneFirst: 'Choose one first',
  runningCount: (n: number): string => `${n} running`,
  noEmulator: 'No emulator',
  noGameLoaded: 'No game loaded',
  pauseFirst: 'Pause it and connect again',
  readFrom: (game: string): string => `Read from ${game}`,
  disconnected: 'Disconnected',
  updated: 'Updated',

  /* Rail */
  location: 'Location',
  standing: 'Standing',
  update: 'Update',
  x: 'X',
  y: 'Y',
  z: 'Z',
  facing: 'Facing',
  link: 'Link',
  camera: 'Camera',

  target: 'Target',
  shape: 'Shape',
  point: 'Point',
  range: 'Range',
  address: 'Address',
  aim: 'Aim',
  aimPlayer: 'Player',
  aimOverhead: 'Overhead item',
  aimBomb: 'Bomb/Small Pot',
  tolerance: 'Tolerance',
  all: 'All',
  single: 'Single',
  xMax: 'X max',
  zMax: 'Z max',
  facingMax: 'Facing max',
  zMaxBox: 'Z max',

  bounds: 'Bounds',
  anywhere: 'Anywhere',
  xMin: 'X min',
  zMin: 'Z min',
  sideOpen: 'This side is open',
  closeSide: 'Close this side',
  clickAnEdge: 'Click an edge',
  start: 'start',
  edgeZMax: 'Z max edge',
  edgeZMin: 'Z min edge',
  edgeXMin: 'X min edge',
  edgeXMax: 'X max edge',
  questionWidth: 'Question width',
  locationHeight: 'Location height',
  targetHeight: 'Target height',

  /* Room */
  room: 'Room',
  roomHelp: 'Room. Drag to orbit, the wheel zooms.',
  zoomIn: 'Zoom in',
  zoomOut: 'Zoom out',
  reset: 'Reset',
  dragToOrbit: 'drag to orbit',
  camAt: (yaw: number, zoom: string): string => `yaw ${yaw}° · ${zoom}×`,
  noRoom: 'No room',
  walls: 'walls',
  floors: 'floors',
  roofs: 'roofs',

  /* Answers */
  plansPanel: 'Plans',
  sequence: 'Sequence',
  sequenceHeight: 'Sequence height',
  answersWidth: 'Answers width',
  off: 'Off',
  /** Signed steps per missed axis (+ past, - short), x first; axes that hit are omitted. */
  offAxes: (steps: number[]): string => steps.filter(n => n !== 0)
    .map(n => `${n > 0 ? '+' : '-'}${Math.abs(n).toLocaleString()}`).join(' '),
  totalCol: 'Total',
  item: 'Item',
  reachesWord: 'reaches',
  missesWord: 'misses',
  nothingYet: 'Nothing yet',
  nothingFound: 'Nothing found',
  plansArrive: 'Plans arrive as they are found',
  stoppedBeforeAny: 'The run was stopped before it found any',
  noMoves: 'No moves',
  waiting: 'Waiting',
  dash: '—',
  framesCount: (n: number): string => `${n} frames`,
  playTab: '← Play',
  plansTab: 'Plans →',
  stop: 'Stop',
  percent: (n: number): string => `${n}%`,
  verifiedFigure: 'Verified',
  engineFigure: 'Engine',
  memoryFigure: 'Memory',
  memoryFull: 'Memory full; search no longer exhaustive',
  stopped: 'Stopped',
  searchBroke: 'An error occurred during the search',
  noValidTargets: 'No valid targets for this geometry',
  noDiscTargets: 'Unable to show targets: Connect ISO',
  doneWord: 'Done',
  stopToChange: 'Stop the search to change it',
  reachCount: (n: number): string => `${n} reach`,

  /** The sign is the turn direction and part of the input: +95 and -5 are different facings. */
  turnSteps: (name: string, n: number): string => `${name} ${n > 0 ? '+' : ''}${n}`,
  /** `L + C Down Turnaround`, 2 becomes `L + C Down, x2 L Turnaround`. */
  lTaps: (name: string, n: number): string => `${name.replace(/ Turnaround$/, '')}, x${n} L Turnaround`,
  noneReach: 'None reach',

  /* Run bar */
  search: 'Search',
  collision: 'Collision',
  none: 'None',
  groundFloors: 'Floors',
  solid: 'Solid',
  actors: 'Actors',
  sword: 'Sword',
  needsFloors: 'Needs floors',
  needsWalls: 'Needs walls',
  steps: 'Steps',
  frames: 'Frames',
  notStarted: 'Not started',
  logs: 'Logs',

  blockedEmpty: (box: string): string => `${box} is empty`,

  blockedNoMoves: 'No moves chosen',
  blockedAddress: 'Address must be 4 sequential bytes or less',

  /* Address */
  noNumber: 'no number',
  minWord: 'min',
  maxWord: 'max',
  blankByte: 'Blank: this byte is not decided',
  notHex: (slot: string): string => `${slot} is not hex`,

  /* Windows */
  close: 'Close',
  done: 'Done',
  copy: 'Copy',
  copied: 'Copied',
  messages: 'Messages',
  somethingBroke: 'Something broke',
  noMatch: 'No match',
  nothingChosen: 'Nothing chosen',

  /* Logs */
  time: 'Time',
  type: 'Type',
  details: 'Details',
  oneLine: '1 line',
  lines: (n: number): string => `${n} lines`,
  logsEmptyWhy: 'Whatever the app says arrives here',

  /* Stage */
  stage: 'Stage',
  chooseStage: 'Choose a stage and room',
  wallsCol: 'Walls',
  stageRooms: (stage: string, rooms: number): string =>
    `${stage} · ${rooms} ${rooms === 1 ? 'room' : 'rooms'}`,
  roomAt: (stage: string, room: number): string => `${stage} · room ${room}`,

  /* Options */
  machine: 'Machine',
  disc: 'Disc',
  game: 'Game',
  gameFile: 'Game file',
  noFile: 'No file',
  browse: 'Browse',
  attachIso: 'Attach ISO',
  cores: 'Cores',
  ofCores: (n: number) => `of ${n}`,
  checkRange: 'Check range',
  hex: 'Hex',
  saveMoves: 'Save moves',
  saveSession: 'Save session',
  plans: 'Plans',
  solutions: 'Solutions',
  updates: 'Updates',
  check: 'Check',
  looking: 'Looking',
  clear: 'Clear',
  cancel: 'Cancel',
  warning: 'Warning',
  version: '1.4.0',
  planBytes: '1.4 MB',
  solBytes: '18.6 MB',
  noBytes: '0 B',
  clearPlans: 'Clear plans',
  clearSolutions: 'Clear solutions',
  cannotUndo: 'This cannot be undone',
  plansCleared: 'Plans cleared',
  solutionsCleared: 'Solutions cleared',
  plansKept: 'Plans kept',
  plansNotKept: 'Plans not kept',
  gameAttached: 'Game file attached',
  gameRemoved: 'Game file removed',
  noNewerVersion: 'No newer version',
  infoGame: 'Reads collision and the stage list from a game disc',
  infoCores: 'How many threads the search runs on',
  infoHex: 'Shows and takes every facing as hex',
  infoKeepMoves: 'Automatically save moves between sessions',
  infoRestore: 'Automatically loads last session',
  infoPlans: 'Keeps found plans on disc between sessions',
  infoSolutions: 'Keeps searches that have been solved, so they are not run twice',
  infoUpdates: 'Looks for a newer version',

  /* Moves */
  showAll: 'Show All',
  noSword: 'No sword',
  swordAway: 'Away',
  swordOut: 'Out',
  swordBoth: 'Both',
  move: 'Move',
  chosenCol: 'Chosen',
  presses: 'Presses',
  sort: 'Sort',
  name: 'Name',
  min: 'min',
  max: 'max',
  fewestFrames: 'Fewest frames',
  mostFrames: 'Most frames',
  searchDecidesOrder: 'The search decides this order',
  chooseTypeFirst: 'Choose a type first',
  noMovesChosen: 'No moves chosen',
  movesCount: (n: number): string => `${n.toLocaleString()} moves`,
  framesOf: (move: string): string => `${move} frames`,
  needsWholeFrames: (move: string): string => `${move} needs whole frames`,
  pressesRange: (max: number): string => `Presses are 1 to ${max}`,

  stateEmpty: 'Empty',
} as const;

export type Strings = typeof t;
